### PR TITLE
add raid detection and banning

### PR DESCRIPTION
**Pull request by awsomearvinder**

### CODE REVIEW

**Comment by Ganoosh** [comment]
Possibly change how the config works to fit #15

**Comment by awsomearvinder** [comment]
@Ganoosh When you have some free time do you wanna take a look and see if you can understand how the code works?

I tried to make it cleaner and easier to understand the logic behind it - it's still largely untested. (I'm planning on merging it in and just having it log who it would of banned, instead of actually banning)

**Comment by Ganoosh** [comment]
@awsomearvinder sure, I'm gone right now, but I'll be home by Monday.

**Comment by awsomearvinder** [comment]
Sure thing.

**Comment by Ganoosh** [comment]
I checked over the code, I think it's good, but I don't see why we don't just have the user fill out a captcha upon them joining.

At the moment we have every user type the word rock into a verification channel, why don't we just override that by dm'ing the user a captcha and then giving them the member role if completed successfully. 

To address the concern of the raider dm'ing people, after thinking for awhile, I realized that the raider cannot dm anyone who doesn't have access to the channel. So all we need to do is simply revoke access from the verification channel from normal users ( which is already done)

By doing that the user has no possible way of dm'ing anyone except admins and mods.

I could also see this being paired with what you already have, except if raid mode is currently active, the user has to fail the captcha before they are banned. Whereas if its inactive we give them 3 chances before they are banned.
----- 
But to be fair, I'm not exactly sure how user bot's work and if they can break the guidelines of a normal user by getting a list of all server members, if this is true, me and quake's idea is completely useless.

**Comment by awsomearvinder** [comment]
We do want some ban action though as the mods do like to go through and ban all the bots as they could accidentally make another channel or something that normal people could view without being verified, causing mayhem from discord raiders.

**Comment by awsomearvinder** [comment]
corpbot does this and I don't really see any merit in duplicating this functionality.

**Pull request closed without merging**
